### ISSUE TITLE
Bad link to docs on github.io project site

### ISSUE THREAD

**Issue by nate-opti** [erichiggins/gaek#5]
The auto-generated https://erichiggins.github.io/gaek/ site has the below link to a readthedocs page, which doesn't exist:

<img width="493" alt="screen shot 2015-12-28 at 1 14 57 pm" src="https://cloud.githubusercontent.com/assets/6729884/12023213/339a998a-ad65-11e5-89bc-89fd58f06cd4.png">

I don't think I can submit a PR to update this text since it looks like it's auto-generated from an older version of the gaek readme.

**Comment by erichiggins** [comment]
Oh, interesting. I'll see what I can do about it. Thanks for the heads up!

**Comment by erichiggins** [comment]
@nate-opti Should be good to go. Can you confirm, please?

**Comment by nate-opti** [comment]
LG!
